sudo: required
dist: trusty
language: csharp
solution: Shift.sln
before_install:
- sudo apt-get install --yes graphviz
- sudo apt-get install --yes --no-install-recommends doxygen
after_success:
 - bash Documentation/build-docs.sh