var annotated =
[
    [ "Shift.Graphics.DDS", "class_shift_1_1_graphics_1_1_d_d_s.html", null ],
    [ "Shift.Graphics.DDS.DDS_PIXEL_FORMAT", "struct_shift_1_1_graphics_1_1_d_d_s_1_1_d_d_s___p_i_x_e_l___f_o_r_m_a_t.html", "struct_shift_1_1_graphics_1_1_d_d_s_1_1_d_d_s___p_i_x_e_l___f_o_r_m_a_t" ],
    [ "Shift.Graphics.DDS.DDSURFACEDESC2", "struct_shift_1_1_graphics_1_1_d_d_s_1_1_d_d_s_u_r_f_a_c_e_d_e_s_c2.html", "struct_shift_1_1_graphics_1_1_d_d_s_1_1_d_d_s_u_r_f_a_c_e_d_e_s_c2" ],
    [ "Shift.Game", "class_shift_1_1_game.html", "class_shift_1_1_game" ],
    [ "Shift.Input.GamePad", "class_shift_1_1_input_1_1_game_pad.html", null ],
    [ "Shift.GameTime", "class_shift_1_1_game_time.html", "class_shift_1_1_game_time" ],
    [ "Shift.GameWindow", "class_shift_1_1_game_window.html", "class_shift_1_1_game_window" ],
    [ "Shift.Graphics.GL.GLShortcut", "class_shift_1_1_graphics_1_1_g_l_1_1_g_l_shortcut.html", "class_shift_1_1_graphics_1_1_g_l_1_1_g_l_shortcut" ],
    [ "Shift.Graphics.GL.GLSLLexer", "class_shift_1_1_graphics_1_1_g_l_1_1_g_l_s_l_lexer.html", "class_shift_1_1_graphics_1_1_g_l_1_1_g_l_s_l_lexer" ],
    [ "Shift.Graphics.GL.GLStatic", "class_shift_1_1_graphics_1_1_g_l_1_1_g_l_static.html", null ],
    [ "Shift.Input.Joystick", "class_shift_1_1_input_1_1_joystick.html", null ],
    [ "Shift.Input.Keyboard", "class_shift_1_1_input_1_1_keyboard.html", "class_shift_1_1_input_1_1_keyboard" ],
    [ "Shift.Input.KeyboardState", "struct_shift_1_1_input_1_1_keyboard_state.html", "struct_shift_1_1_input_1_1_keyboard_state" ],
    [ "Shift.Input.Util.KeyboardUtil", "class_shift_1_1_input_1_1_util_1_1_keyboard_util.html", "class_shift_1_1_input_1_1_util_1_1_keyboard_util" ],
    [ "Shift.Graphics.GL.GLSLLexer.Line", "class_shift_1_1_graphics_1_1_g_l_1_1_g_l_s_l_lexer_1_1_line.html", "class_shift_1_1_graphics_1_1_g_l_1_1_g_l_s_l_lexer_1_1_line" ],
    [ "Shift.MathHelper", "class_shift_1_1_math_helper.html", "class_shift_1_1_math_helper" ],
    [ "Shift.Matrix", "struct_shift_1_1_matrix.html", "struct_shift_1_1_matrix" ],
    [ "Shift.Input.Mouse", "class_shift_1_1_input_1_1_mouse.html", "class_shift_1_1_input_1_1_mouse" ],
    [ "Shift.Input.MouseState", "struct_shift_1_1_input_1_1_mouse_state.html", "struct_shift_1_1_input_1_1_mouse_state" ],
    [ "Shift.Plane", "struct_shift_1_1_plane.html", "struct_shift_1_1_plane" ],
    [ "Shift.PlaneHelper", "class_shift_1_1_plane_helper.html", "class_shift_1_1_plane_helper" ],
    [ "Shift.Platform", "class_shift_1_1_platform.html", "class_shift_1_1_platform" ],
    [ "Shift.Point", "struct_shift_1_1_point.html", "struct_shift_1_1_point" ],
    [ "Shift.Graphics.GL.ProgramParam", "class_shift_1_1_graphics_1_1_g_l_1_1_program_param.html", "class_shift_1_1_graphics_1_1_g_l_1_1_program_param" ],
    [ "Shift.Quaternion", "struct_shift_1_1_quaternion.html", "struct_shift_1_1_quaternion" ],
    [ "Shift.Rectangle", "struct_shift_1_1_rectangle.html", "struct_shift_1_1_rectangle" ],
    [ "Shift.Graphics.GL.Shader", "class_shift_1_1_graphics_1_1_g_l_1_1_shader.html", "class_shift_1_1_graphics_1_1_g_l_1_1_shader" ],
    [ "Shift.Graphics.GL.ShaderProgram", "class_shift_1_1_graphics_1_1_g_l_1_1_shader_program.html", "class_shift_1_1_graphics_1_1_g_l_1_1_shader_program" ],
    [ "Shift.Graphics.SpriteBatch", "class_shift_1_1_graphics_1_1_sprite_batch.html", null ],
    [ "Shift.Graphics.Texture", "class_shift_1_1_graphics_1_1_texture.html", "class_shift_1_1_graphics_1_1_texture" ],
    [ "Shift.Graphics.GL.GLSLLexer.Token", "class_shift_1_1_graphics_1_1_g_l_1_1_g_l_s_l_lexer_1_1_token.html", "class_shift_1_1_graphics_1_1_g_l_1_1_g_l_s_l_lexer_1_1_token" ],
    [ "Shift.Vector2", "struct_shift_1_1_vector2.html", "struct_shift_1_1_vector2" ],
    [ "Shift.Vector3", "struct_shift_1_1_vector3.html", "struct_shift_1_1_vector3" ],
    [ "Shift.Vector4", "struct_shift_1_1_vector4.html", "struct_shift_1_1_vector4" ]
];