var files =
[
    [ "Shift/Game.cs", "_game_8cs.html", null ],
    [ "Shift/GameTime.cs", "_game_time_8cs.html", null ],
    [ "Shift/GameWindow.cs", "_game_window_8cs.html", null ],
    [ "Shift/Platform.cs", "_platform_8cs.html", null ],
    [ "Shift/Graphics/SpriteBatch.cs", "_sprite_batch_8cs.html", null ],
    [ "Shift/Graphics/Texture.cs", "_texture_8cs.html", null ],
    [ "Shift/Graphics/GL/GlEnum.cs", "_gl_enum_8cs.html", "_gl_enum_8cs" ],
    [ "Shift/Graphics/GL/GlShortcut.cs", "_gl_shortcut_8cs.html", null ],
    [ "Shift/Graphics/GL/GLSLLexer.cs", "_g_l_s_l_lexer_8cs.html", null ],
    [ "Shift/Graphics/GL/GLStatic.cs", "_g_l_static_8cs.html", null ],
    [ "Shift/Graphics/GL/Shader.cs", "_shader_8cs.html", "_shader_8cs" ],
    [ "Shift/Input/GamePad.cs", "_game_pad_8cs.html", null ],
    [ "Shift/Input/Joystick.cs", "_joystick_8cs.html", null ],
    [ "Shift/Input/Keyboard.cs", "_keyboard_8cs.html", null ],
    [ "Shift/Input/Keys.cs", "_keys_8cs.html", "_keys_8cs" ],
    [ "Shift/Input/Mouse.cs", "_mouse_8cs.html", null ],
    [ "Shift/Input/States/ButtonState.cs", "_button_state_8cs.html", "_button_state_8cs" ],
    [ "Shift/Input/States/KeyboardState.cs", "_keyboard_state_8cs.html", null ],
    [ "Shift/Input/States/KeyState.cs", "_key_state_8cs.html", "_key_state_8cs" ],
    [ "Shift/Input/States/MouseState.cs", "_mouse_state_8cs.html", null ],
    [ "Shift/Input/Util/KeyboardUtil.cs", "_keyboard_util_8cs.html", null ],
    [ "Shift/Math/MathHelper.cs", "_math_helper_8cs.html", null ],
    [ "Shift/Math/Matrix.cs", "_matrix_8cs.html", null ],
    [ "Shift/Math/Plane.cs", "_plane_8cs.html", null ],
    [ "Shift/Math/Point.cs", "_point_8cs.html", null ],
    [ "Shift/Math/Quaternion.cs", "_quaternion_8cs.html", null ],
    [ "Shift/Math/Rectangle.cs", "_rectangle_8cs.html", null ],
    [ "Shift/Math/Vector2.cs", "_vector2_8cs.html", null ],
    [ "Shift/Math/Vector3.cs", "_vector3_8cs.html", null ],
    [ "Shift/Math/Vector4.cs", "_vector4_8cs.html", null ],
    [ "Shift/obj/Release/.NETFramework,Version=v4.5.2.AssemblyAttribute.cs", "_8_n_e_t_framework_00_version_0Av4_85_82_8_assembly_attribute_8cs.html", null ],
    [ "Shift/Properties/AssemblyInfo.cs", "_assembly_info_8cs.html", null ]
];